# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: mysql
  pool: 5
  timeout: 5000
development:
   adapter: mysql2
   database: Project4
   username: root
   password: root
   host: localhost
   port: 3306

test:
   adapter: mysql2
   database: Project4
   username: root
   password: root
   host: localhost
   port: 3306
production:
   adapter: mysql2
   database: Project4
   username: root
   password: root
   host: localhost
   port: 3306