# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 97791d727feed9ecd25d31df304be26840774b3bd6448f7ce7ab362cb8b7597406badf175e0e50644eb3988005f0e53a4b4b0737ea06c5b9370f0e3e60016023

test:
  secret_key_base: eaa638b038a44f5debd59cb0b1abbf43288be6ad084be63272c1f75f0ba4c5d498ef570229a8ff7fb4767b8b042e0ce880635cc54109c23338d5f477ee77c7ae

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
